<a href="https://colab.research.google.com/github/rohitblpprajapat/100-days-of-code/blob/master/notebook8579ba2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [51]:
# ex 1
np.__version__

'2.0.2'

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# make a 3x3 boolean matrix
np.full((3,3), True)

np.full((9), True, dtype=bool).reshape(3,3)

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [54]:
# 4 extract itmes with condition
x = np.arange(10)

x[x%2 == 0]

x[x>3]


array([4, 5, 6, 7, 8, 9])

In [55]:
# 5 replace items which satisfy condition

x = np.arange(10)

x[x%2 == 0] = 0

x

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [56]:
arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [58]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array')
out

print('\nOriginal Array')
arr


Modified Array

Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# 7. How to reshape an array?
arr = np.arange(10)
arr.reshape(2,5)

# Another solution
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
#  8. How to stack two arrays vertically?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
# 9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [62]:
# 10. How to generate custom sequences in numpy without hardcoding?

a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

#other solution
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [63]:
# 11. How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [64]:
# 12. How to remove from one array those items that exist in another?

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [65]:
# 13. How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [67]:
# 14 extract all numbers between given range eg. range(5,51)
import random
a = np.array([random.randint(1,100) for _ in range(10)])

a[(a >=5) & (a <= 50)]



array([26, 34, 17, 23,  8])

In [73]:
# 15 make a python function that handles scalars to work on numpy arrays


def maxx(x,y):
  return (x if x > y else y)

def pair_max(x,y):
  maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b), x,y)]
  return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)


array([6, 7, 9, 8, 9, 7, 5])

In [ ]:
# 16 swap two colums in 2d np array

array = np.