<a href="https://colab.research.google.com/github/rohitblpprajapat/100-days-of-code/blob/master/notebook8579ba2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [56]:
# ex 1
np.__version__

'2.0.2'

In [57]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# make a 3x3 boolean matrix
np.full((3,3), True)

np.full((9), True, dtype=bool).reshape(3,3)

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [59]:
# 4 extract itmes with condition
x = np.arange(10)

x[x%2 == 0]

x[x>3]


array([4, 5, 6, 7, 8, 9])

In [60]:
# 5 replace items which satisfy condition

x = np.arange(10)

x[x%2 == 0] = 0

x

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [61]:
arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [62]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array')
out

print('\nOriginal Array')
arr


Modified Array

Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# 7. How to reshape an array?
arr = np.arange(10)
arr.reshape(2,5)

# Another solution
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
#  8. How to stack two arrays vertically?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [65]:
# 9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [66]:
# 10. How to generate custom sequences in numpy without hardcoding?

a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

#other solution
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [67]:
# 11. How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [68]:
# 12. How to remove from one array those items that exist in another?

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [69]:
# 13. How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [70]:
# 14 extract all numbers between given range eg. range(5,51)
import random
a = np.array([random.randint(1,100) for _ in range(10)])

a[(a >=5) & (a <= 50)]



array([31, 15, 29, 29])

In [71]:
# 15 make a python function that handles scalars to work on numpy arrays


def maxx(x,y):
  return (x if x > y else y)

def pair_max(x,y):
  maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b), x,y)]
  return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)


array([6, 7, 9, 8, 9, 7, 5])

In [72]:
# 16 swap two colums in 2d np array

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[:, [1,0,2]]

Original array

Modified array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [73]:
# 17. How to swap two rows in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
print('Original array')
arr

# Solution

print("\nModified array")
arr[[1,0,2], :]


Original array

Modified array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [74]:
# 18. How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[::-1, :]

Original array

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [75]:
# 19. How to reverse the columns of a 2D array?

arr = np.arange(9).reshape(3,3)
print('Original array')
arr


print("\nModified array")
arr[:, ::-1]

Original array

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [76]:
# 20. How to create a 2D array containing random floats between 5 and 10?

rand_arr = np.random.uniform(5,10, size=(5,3))

rand_arr

array([[8.54 , 5.103, 9.85 ],
       [9.162, 6.062, 5.909],
       [5.917, 6.521, 7.624],
       [7.16 , 6.456, 8.059],
       [5.697, 6.461, 6.832]])

In [77]:
from numpy.random.mtrand import rand
# 21 Print only 3 decimal placess in np arraya

rand_arr = np.random.random((5,3))
rand_arr

np.set_printoptions(precision=3)

rand_arr

array([[0.456, 0.785, 0.2  ],
       [0.514, 0.592, 0.046],
       [0.608, 0.171, 0.065],
       [0.949, 0.966, 0.808],
       [0.305, 0.098, 0.684]])

In [78]:
# 22 prerry print np array

np.random.seed(42)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)

print(rand_arr)

np.set_printoptions(suppress=True) # suppress removes chaos for very small values
print(rand_arr)



[[3.745e-04 9.507e-04 7.320e-04]
 [5.987e-04 1.560e-04 1.560e-04]
 [5.808e-05 8.662e-04 6.011e-04]]
[[0.    0.001 0.001]
 [0.001 0.    0.   ]
 [0.    0.001 0.001]]


In [79]:
# 23 limit the no of items printed

a = np.arange(100)

np.set_printoptions(threshold=99, edgeitems=2)
print(a)

[ 0  1 ... 98 99]


In [80]:
# 24. How to print the full numpy array without truncating
a = np.arange(15)


np.set_printoptions(threshold=200) #just increase the threshold
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [81]:
# 25 how to import a dataset with numbers and texts keepint the text intact in np

housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',',dtype=object)
housing_data



array([[b'"longitude"', b'"latitude"', ..., b'"median_income"',
        b'"median_house_value"'],
       [b'-114.310000', b'34.190000', ..., b'1.493600', b'66900.000000'],
       ...,
       [b'-124.300000', b'41.800000', ..., b'1.979700', b'85800.000000'],
       [b'-124.350000', b'40.540000', ..., b'3.014700', b'94600.000000']],
      dtype=object)