<a href="https://colab.research.google.com/github/rohitblpprajapat/100-days-of-code/blob/master/notebook8579ba2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# ex 1
np.__version__

'2.0.2'

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# make a 3x3 boolean matrix
np.full((3,3), True)

np.full((9), True, dtype=bool).reshape(3,3)

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
# 4 extract itmes with condition
x = np.arange(10)

x[x%2 == 0]

x[x>3]


array([4, 5, 6, 7, 8, 9])

In [15]:
# 5 replace items which satisfy condition

x = np.arange(10)

x[x%2 == 0] = 0

x

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])