<a href="https://colab.research.google.com/github/rohitblpprajapat/100-days-of-code/blob/master/notebook8579ba2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# ex 1
np.__version__

'2.0.2'

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# make a 3x3 boolean matrix
np.full((3,3), True)

np.full((9), True, dtype=bool).reshape(3,3)

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# 4 extract itmes with condition
x = np.arange(10)

x[x%2 == 0]

x[x>3]


array([4, 5, 6, 7, 8, 9])

In [6]:
# 5 replace items which satisfy condition

x = np.arange(10)

x[x%2 == 0] = 0

x

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [7]:
arr = np.arange(10)

arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(10)

out = arr.copy()

out[out%2 == 1] = -1

print('Modified Array')
out

print('\nOriginal Array')
arr


Modified Array

Original Array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 7. How to reshape an array?
arr = np.arange(10)
arr.reshape(2,5)

# Another solution
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
#  8. How to stack two arrays vertically?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
# 9. How to stack two arrays horizontally?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [12]:
# 10. How to generate custom sequences in numpy without hardcoding?

a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

#other solution
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
# 11. How to get the common items between two python numpy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

In [14]:
# 12. How to remove from one array those items that exist in another?

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [15]:
# 13. How to get the positions where elements of two arrays match?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [16]:
# 14 extract all numbers between given range eg. range(5,51)
import random
a = np.array([random.randint(1,100) for _ in range(10)])

a[(a >=5) & (a <= 50)]



array([35, 14, 38, 35, 20])

In [17]:
# 15 make a python function that handles scalars to work on numpy arrays


def maxx(x,y):
  return (x if x > y else y)

def pair_max(x,y):
  maximum = [maxx(a,b) for a,b in map(lambda a,b:(a,b), x,y)]
  return np.array(maximum)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a,b)


array([6, 7, 9, 8, 9, 7, 5])

In [18]:
# 16 swap two colums in 2d np array

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[:, [1,0,2]]

Original array

Modified array


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [19]:
# 17. How to swap two rows in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
print('Original array')
arr

# Solution

print("\nModified array")
arr[[1,0,2], :]


Original array

Modified array


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [20]:
# 18. How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)

print('Original array')
arr

# Solution

print("\nModified array")
arr[::-1, :]

Original array

Modified array


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [21]:
# 19. How to reverse the columns of a 2D array?

arr = np.arange(9).reshape(3,3)
print('Original array')
arr


print("\nModified array")
arr[:, ::-1]

Original array

Modified array


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [22]:
# 20. How to create a 2D array containing random floats between 5 and 10?

rand_arr = np.random.uniform(5,10, size=(5,3))

rand_arr

array([[8.52052463, 8.49357591, 8.75791179],
       [7.88745045, 9.25984967, 7.25153629],
       [8.56793158, 6.37888201, 8.80885751],
       [6.01331464, 8.38432655, 6.03725866],
       [9.13857358, 9.5280476 , 8.45118401]])

In [23]:
from numpy.random.mtrand import rand
# 21 Print only 3 decimal placess in np arraya

rand_arr = np.random.random((5,3))
rand_arr

np.set_printoptions(precision=3)

rand_arr

array([[0.104, 0.51 , 0.028],
       [0.337, 0.154, 0.241],
       [0.715, 0.382, 0.261],
       [0.588, 0.307, 0.792],
       [0.843, 0.973, 0.82 ]])

In [24]:
# 22 prerry print np array

np.random.seed(42)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=False)

print(rand_arr)

np.set_printoptions(suppress=True) # suppress removes chaos for very small values
print(rand_arr)



[[3.745e-04 9.507e-04 7.320e-04]
 [5.987e-04 1.560e-04 1.560e-04]
 [5.808e-05 8.662e-04 6.011e-04]]
[[0.    0.001 0.001]
 [0.001 0.    0.   ]
 [0.    0.001 0.001]]


In [25]:
# 23 limit the no of items printed

a = np.arange(100)

np.set_printoptions(threshold=99, edgeitems=2)
print(a)

[ 0  1 ... 98 99]


In [26]:
# 24. How to print the full numpy array without truncating
a = np.arange(15)


np.set_printoptions(threshold=200) #just increase the threshold
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# 25 how to import a dataset with numbers and texts keepint the text intact in np

housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',',dtype=object)
housing_data



array([[b'"longitude"', b'"latitude"', ..., b'"median_income"',
        b'"median_house_value"'],
       [b'-114.310000', b'34.190000', ..., b'1.493600', b'66900.000000'],
       ...,
       [b'-124.300000', b'41.800000', ..., b'1.979700', b'85800.000000'],
       [b'-124.350000', b'40.540000', ..., b'3.014700', b'94600.000000']],
      dtype=object)

In [28]:
# 26 how to extract a particular column from 1D arr of touples


housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',', usecols=[-1],dtype=object)

housing_data

array([b'"median_house_value"', b'66900.000000', ..., b'85800.000000',
       b'94600.000000'], dtype=object)

In [29]:
# 27 how to convert a 1D array of touples to a 2D np array

housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',',skip_header=1, usecols=[-1, -2],dtype=float)

housing_data

array([[66900.   ,     1.494],
       [80100.   ,     1.82 ],
       ...,
       [85800.   ,     1.98 ],
       [94600.   ,     3.015]])

In [30]:
# 28 compute the mean, mode, median and standard deviation of a np array
import pandas as pd

housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',', usecols=[-1], skip_header=1,dtype=float)
# mean
print("mean",np.mean( housing_data))

# median
print('medeian', np.median(housing_data))

# mode
value, counts = np.unique(housing_data, return_counts=True)
max_value_index = np.argmax(counts)
print("mode: ", value[max_value_index])

# sd
print("SD", np.std(housing_data))



mean 207300.91235294117
medeian 180400.0
mode:  500001.0
SD 115980.35304985354


In [31]:
value, counts = np.unique(housing_data, return_counts=True)
pd.DataFrame(value,counts)

,0
4,14999.0
1,17500.0
3,22500.0
1,25000.0
1,26600.0
...,...
1,498800.0
1,499000.0
1,499100.0
22,500000.0


In [32]:
# 29 normalize an array

housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',',skip_header=1, usecols=[-1],dtype=float)

norm_housing_data = (housing_data - np.min(housing_data))/(np.max(housing_data - np.min(housing_data)))
housing_data


array([66900., 80100., ..., 85800., 94600.])

In [33]:
# 30 compute the softmaxt score

housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',', skip_header=1, usecols=[-1],dtype=float)


# softmax = np.exp(housing_data)/(sum(np.exp(housing_data))) ## memory overflow problem for 64 bit if  > e^709 to resolve this we can use normalized data
exp_data = np.exp(norm_housing_data)

softmax = exp_data/sum(exp_data)
softmax

sum(softmax) # should be 1

np.float64(0.9999999999999708)

In [34]:
# 31 find percentile scores
# let's find the 25th 90th percentile
housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',', skip_header=1, usecols=[-1],dtype=float)

np.percentile(housing_data, q=[25,90])


array([119400., 379600.])

In [35]:
# 32 Insrt values at random positions
# Insert np.nan values at 20 random positions in housing dataset


housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',', skip_header=1, usecols=[-1],dtype=float)

for i in np.random.randint(0, len(housing_data), 20):
  housing_data[i] = np.nan

np.sum(np.isnan(housing_data))



np.int64(20)

In [36]:
# 33 find the position of missing values in np array

np.isnan(housing_data).sum()

np.int64(20)

In [42]:
housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',', skip_header=1,dtype=float)


housing_data[np.random.randint(len(housing_data), size=20), np.random.randint(9, size=20)] = np.nan

print("Number of missing values in housing data: \n", np.isnan(housing_data[:, :]).sum())

# Find total mising value in 1D data
print("Number of missing values in any one feature of housing data: \n", np.isnan(housing_data[:, 0]).sum())

print("Position of missing values: \n", np.where(np.isnan(housing_data[:, 0])))

Number of missing values in housing data: 
 20
Number of missing values in any one feature of housing data: 
 2
Position of missing values: 
 (array([ 1636, 13545]),)


In [54]:
# 34 filete a numpy array based on two or more conditions

housing_data = np.genfromtxt('/content/sample_data/california_housing_train.csv',
                             delimiter=',', skip_header=1,dtype=float)

housing_data[(housing_data[:, 2] > 20) & (housing_data[:,0] < 300)]



array([[ -114.58 ,    33.63 , ...,     3.344, 74000.   ],
       [ -114.58 ,    33.61 , ...,     2.677, 82400.   ],
       ...,
       [ -124.27 ,    40.69 , ...,     2.518, 79000.   ],
       [ -124.35 ,    40.54 , ...,     3.015, 94600.   ]])

In [ ]:
# 35 drop rows that conatian a missing value

